version: '3'

networks:
  halvonik-api:

services:
  halvonik-php:
    build:
      context: .
      dockerfile: test/Dockerfile
    image: ppsdocker/halvonik-php
    container_name: HalvonikPhp
    command:
      - sh
      - '-c'
      - /entrypoint.sh
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 10G
        reservations:
          cpus: '0.25'
          memory: 20M
    expose:
      - 9000
    networks:
      - halvonik-api
    volumes:
      - ./src:/var/www/halvonik_api

  halvonik-web:
    image: library/nginx:1.20.1
    container_name: HalvonikWeb
    ports:
      - "8086:80"
    networks:
      - halvonik-api
    depends_on:
      - halvonik-php
    volumes:
      - ./src:/var/www/halvonik_api
      - ./default.conf:/etc/nginx/conf.d/default.conf