kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: ukf
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 33%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            defaultMode: 420
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: ukf-secret
      containers:
        - name: php8
          image: library/php:8.2.2-fpm
          imagePullPolicy: Always
          command:
            - /usr/local/sbin/php-fpm
            - '--force-stderr'
            - '--nodaemonize'
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
          resources:
            requests:
              memory: 200Mi
              cpu: "0.12"
            limits:
              memory: 300Mi
              cpu: "0.25"
        - name: nginx
          image: library/nginx:1.20.1
          imagePullPolicy: Always
          command:
            - /usr/sbin/nginx
            - '-g'
            - daemon off;
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/sbin/nginx
                  - '-s'
                  - quit
          resources:
            requests:
              memory: 200Mi
              cpu: "0.12"
            limits:
              memory: 300Mi
              cpu: "0.25"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf